### ISSUE TITLE
Assorted Problems Running The Integration Tests

### ISSUE THREAD

**Issue by daveaglick** [octokit/octokit.net#749] opened 2015-03-10 19:48 UTC
I am having an issue starring repositories for an authenticated user. For example:

```
GitHubClient github = new GitHubClient(new ProductHeaderValue("My Product"));
github.Credentials = new Credentials("12345...");
var result = await github.Activity.Starring.StarRepo("octokit", "octokit.net");
```

In this case, `result` is always false and the repository does not get starred. I attempted to track down what might be causing this, and I suspect it has to do with this condition in the API docs:

> Note that you’ll need to set `Content-Length` to zero when calling out to this endpoint.

Further, this is from the API docs regarding `PUT` requests:

> For `PUT` requests with no `body` attribute, be sure to set the `Content-Length` header to zero.

In `Connection.SendDataInternal<T>()` I see that there actually is a check to see if a body is passed in, but it just sets the body and doesn't add the appropriate header if one isn't found. In fact, I can't find the string `Content-Length` anywhere in the project.

Does this sound reasonable? Wanted to check before doing any work because it seems unlikely that I would be the first to notice that `StarRepo()` doesn't work at all. If it sounds like I'm on to something, I can go ahead and create a PR - I'm assuming that the fix should be to check for a body in `Connection.SendDataInternal<T>()` and if one isn't found and the `Request.Method` is `PUT`, to set the `Content-Length` header to 0.

Last question is how are the integration tests handled? I see that there aren't currently any for the `StarredClient` - would a test be needed for this change?

**Comment by shiftkey** [comment] 2015-03-11 06:00
@somedave thanks for the detailed writeup.

We have similar behaviour for starring and unstarring Gists, and I've not seen the [integration tests](https://github.com/octokit/octokit.net/blob/master/Octokit.Tests.Integration/Clients/GistsClientTests.cs#L59-L70) fail in this way.

For a starting point, I'd add a failing integration test for this - steal some of the code from [here](https://github.com/octokit/octokit.net/blob/master/Octokit.Tests.Integration/Clients/GistsClientTests.cs) and adapt it accordingly to get you started.

**Comment by somedave** [comment] 2015-03-11 14:45
Are there any known issues with timing on the integration tests? I've set up a test account and organization, set the environment variables, gotten the tests to run, etc. However, most of the tests are failing with a `NotFoundException`. When I look at the test account, I do see a whole bunch of time-stamped repositories were created, so it's not a credentials problem. I obviously need to get past execution of the existing tests before thinking about creating new ones...

**Comment by somedave** [comment] 2015-03-11 14:55
Also, has anyone else reported issues getting the tests to show up in Visual Studio (I'm using VS 2013 Pro Update 4)? My Test Explorer is empty and I've attempted to clear the cache as recommended at http://xunit.github.io/docs/running-tests-in-vs.html without success. It would be easier to troubleshoot the issues I'm having with the integration tests if I could run them in isolation from VS and/or debug them without having to use the build script each time. Unfortunately, I'm not familiar enough with FAKE, F#, or xUnit to figure out from the FAKE script what commands to run from the prompt.

**Comment by somedave** [comment] 2015-03-11 15:13
So it turns out I'm getting the following exception from the xUnit test runner during discover:

```
[xUnit.net 00:00:01.6462406] Exception discovering tests from Octokit.Tests.Integration.dll: System.TypeLoadException: Method 'Find' in type 'Xunit.Sdk.XunitTestFrameworkDiscoverer' from assembly 'xunit.execution, Version=2.0.0.2785, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c' does not have an implementation.
```

I guess that makes this an xUnit problem, so I'll see if I can follow up there.

Sorry for the comment flood. Just getting frustrated that it's taking me several hours to set up the build and test environment for what is probably going to be a five minute fix. I'll keep pounding away and try not to spam the issue any more than I have to until I get everything ready for patching.

**Comment by somedave** [comment] 2015-03-11 16:44
So I know I promised I'd keep the comments to a minimum, but this is just too strange.

First, I could not get the Visual Studio xUnit runner to work for the life of me. I played around with it some more and finally got it to consistently hang on discovering tests in `Octokit.Tests.Integration.dll`:
```
------ Discover test started ------
[xUnit.net 00:00:00.0001109] Discovery started
[xUnit.net 00:00:00.3930384] Discovery starting: clean-up-after-tests.exe
[xUnit.net 00:00:00.4190934] Discovery finished: clean-up-after-tests.exe (0 tests)
[xUnit.net 00:00:00.4529852] Skipping: Octokit.Reactive.dll (no reference to xUnit.net)
[xUnit.net 00:00:00.8203221] Discovery starting: Octokit.Tests.Conventions.dll
[xUnit.net 00:00:04.5343658] Discovery finished: Octokit.Tests.Conventions.dll (279 tests)
[xUnit.net 00:00:04.9149537] Discovery starting: Octokit.Tests.Integration.dll
```

Can't get past that point though so, okay, no VS test runner. Figured out how to run from the command line:
```
e:\Code\octokit.net>tools\xunit.runners\tools\xunit.console.exe Octokit.Tests.Integration\bin\Debug\Octokit.Tests.Integration.dll -method "GistsClientTests.CanStarAndUnstarAGist"
xUnit.net console test runner (64-bit .NET 4.0.30319.34209)
Copyright (C) 2014 Outercurve Foundation.

Discovering: Octokit.Tests.Integration
Discovered:  Octokit.Tests.Integration
Starting:    Octokit.Tests.Integration
   GistsClientTests.CanStarAndUnstarAGist [FAIL]
      Assert.True() Failure
      Stack Trace:
         Octokit.Tests.Integration\Clients\GistsClientTests.cs(64,0): at GistsClientTests.<CanStarAndUnstarAGist>d__10.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Finished:    Octokit.Tests.Integration

=== TEST EXECUTION SUMMARY ===
   Octokit.Tests.Integration  Total: 1, Errors: 0, Failed: 1, Skipped: 0, Time: 1.900s
```

The problem is, the test kept failing on different lines. Sometimes it would be the first assertion, sometimes the second, etc. That led me to think it might be a timing problem. I finally got it to consistently succeed by changing the test code (notice the `Thread.Sleep()` calls in-between each API invocation):
```
[IntegrationTest]
public async Task CanStarAndUnstarAGist()
{
    await _fixture.Star(testGistId);

    System.Threading.Thread.Sleep(10000);

    var isStarredTrue = await _fixture.IsStarred(testGistId);
    Assert.True(isStarredTrue);

    System.Threading.Thread.Sleep(10000);

    await _fixture.Unstar(testGistId);

    System.Threading.Thread.Sleep(10000);

    var isStarredFalse = await _fixture.IsStarred(testGistId);
    Assert.False(isStarredFalse);
}
```

It looks like it's got to be a fairly long time too - 4 or 6 seconds wouldn't pass consistently. So that got *this* test passing, but all the other integration tests are a mess on my system. Most fail at arbitrary assertion points that seem to change from one run to the next. That probably just suggests more timing problems, but it does make it hard/impossible to run the entire test suite.

So that's where I'm at, *but here's the really, really strange thing* - when the `CanStarAndUnstarAGist()` test failed part way through, this is what I saw in the GitHub UI:
![image](https://cloud.githubusercontent.com/assets/1020407/6601331/7edf11ce-c7eb-11e4-9bce-3d8b9f35fd14.png)

I waited for a solid 5 minutes thinking it might be some sort of eventual consistency problem, but it never changed. I also tried looking at it in a different browser in case there was some sort of browser caching going on, but it was the same. Once I got the test to pass using the sleep calls, it started acting normally again.

![](http://www.reactiongifs.com/r/2013/11/shrug-house.gif)

So anyway, I've had about as much of this as I can take for a day. I'll come back tomorrow and attempt a test case and WIP PR for starring repos, though at this point it wouldn't surprise me if the issue I initially saw was somehow related to all these other timing problems and isolated to my own environment.

**Comment by khellang** [comment] 2015-03-11 17:10
Cache invalidation is Real Hard™

**Comment by somedave** [comment] 2015-03-11 17:53
Okay, okay, I know I said I'd wait until tomorrow - so sue me.

I wrote a test, and that unexpectedly worked without any additional modifications (with `Thread.Sleep()` calls) but I still couldn't get my little test case to work. In fact, attempting to star from the same user account and same repository in the test and then in LINQPad produced different results until I noticed one difference: the integration tests authenticate with username and password while the LINQPad test I was doing authenticated with a token.

This works (`result == true` and repository gets starred):
```
GitHubClient github = new GitHubClient(new ProductHeaderValue("My Product"));
github.Credentials = new Credentials("[username]", "[password]");
var result = await github.Activity.Starring.StarRepo("octokit", "octokit.net");
```

This does not work (`result == false`, but no exception, and repository does not get starred):
```
GitHubClient github = new GitHubClient(new ProductHeaderValue("My Product"));
github.Credentials = new Credentials("[valid token]");
var result = await github.Activity.Starring.StarRepo("octokit", "octokit.net");
```
I know the token is valid because I can do other things with it like list all the repositories starred by that user.

This throws a `AuthorizationException` (I just changed one character in the token):
```
GitHubClient github = new GitHubClient(new ProductHeaderValue("My Product"));
github.Credentials = new Credentials("[invalid token]");
var result = await github.Activity.Starring.StarRepo("octokit", "octokit.net");
```

So I'm thinking maybe at this point I don't fully understand the GitHub starring API. Sure enough, after a little more digging with additional personal tokens, I learned that starring a repository requires the `public_repo` OAuth scope and not the `user` scope - which doesn't make a whole lot of sense to me since `user` lets you view stars and it seems like starring should be a user-focused activity, but whatever.

Problem solved. Congrats - I'm an idiot and there's nothing wrong with Octokit! (Though I'll add that the odd behavior of the UI after starring through the API is still really strange)

**Comment by shiftkey** [comment] 2015-03-11 20:51
Woah, lots of words here. Sorry to hear about all this pain you're going through just to run my tests :cry:

> I guess that makes this an xUnit problem, so I'll see if I can follow up there.

Hold off on raising this until I've upgraded to xUnit 2.0 RC4 in #725 - I've encountered a similar issue in the past which was subsequently fixed by the team.

> Sure enough, after a little more digging with additional personal tokens, I learned that starring a repository requires the `public_repo` OAuth scope and not the `user` scope - which doesn't make a whole lot of sense to me since user lets you view stars and it seems like starring should be a user-focused activity, but whatever.

This sounds like something I should document in the tests. I'm gonna keep this open and update the title to reflect what went down.

**Comment by somedave** [comment] 2015-03-11 21:19
> Woah, lots of words here.

I tend to do that :)

Thanks for continuing to see this through. Just let me know when/if it would be helpful for me to rerun the tests or try anything else out.

**Comment by shiftkey** [comment] 2015-03-11 21:27
@somedave I'll drop a comment in #725 when that's merged

**Comment by shiftkey** [comment] 2015-04-06 08:29
@daveaglick apologies for not getting back to you sooner.

We're now running xUnit 2 RTM tests on `master` - could you have a go at running the tests again and see if the problem is still present?

**Comment by daveaglick** [comment] 2015-04-07 19:17
Awesome - works great now:

![2015-04-07_15h13_08](https://cloud.githubusercontent.com/assets/1020407/7031387/1a85f0a4-dd39-11e4-83fb-9a7d0983b231.png)

No issues with the VS test runner in VS 2013. Tests that were previously failing or required timeouts appear to be working fine now too.

**Comment by shiftkey** [comment] 2015-04-07 21:07
@daveaglick thanks for confirming

**Closed by shiftkey** 2015-04-07 21:07 UTC
