### ISSUE TITLE
Forced to add System.Net.Http reference before adding it via NuGet in F# project

### ISSUE THREAD

**Issue by gsscoder** [octokit/octokit.net#823] opened 2015-06-19 11:47 UTC
When adding **Octokit** to an F# project (Target Fx: **.NET 4.5**; F# Runtime: **3.1**) via **NuGet**, I'm forced to manually add a reference to `System.Net.Http` or dependency addition fails. This not stopped me to proceed in my project, anyway I thought to report the issue.

It follows VS Package Manager _session_:

``` PowerShell
PM> Install-Package Octokit
Installing 'Octokit 0.13.0'.
Successfully installed 'Octokit 0.13.0'.
Adding 'Octokit 0.13.0' to ThrowIn.Core.
Uninstalling 'Octokit 0.13.0'.
Successfully uninstalled 'Octokit 0.13.0'.
Install failed. Rolling back...
Install-Package : Failed to add reference to 'System.Net.Http'. Please make sure that it is in the Global Assembly Cache.
At line:1 char:1
+ Install-Package Octokit
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand
```

Thank you for sharing the project.

**Comment by shiftkey** [comment] 2015-06-19 11:52
@gsscoder thanks for the details. It's a bit weird the way we add the [System.Net.Http](https://github.com/octokit/octokit.net/blob/master/Octokit.nuspec#L17-L30) reference, but this is the first failure I've heard about it.

What version of VS are you running?

**Comment by khellang** [comment] 2015-06-19 12:33
I've seen this a :hankey:-load of times. I think it's a NuGet screwup. Could you try running `$error[0].Exception.ToString()` in the Package Manager Console?

**Comment by gsscoder** [comment] 2015-06-19 16:31
@shiftkey, absolutely no problem... This happened in Visual Studio 2013 Community Edition (Update 4).

In the attempt to post more data as asked by @khellang, NuGet was not able to connect and grabbed package from local cache: this time it the dependency was correctly added and the package added to the project.

Package Manager session:
```PowerShell
PM> Install-Package Octokit
The source at All [(Aggregate source)] is unreachable. Falling back to NuGet Local Cache at C:\Users\vmuser\AppData\Local\NuGet\Cache
Installing 'Octokit 0.13.0'.
Successfully installed 'Octokit 0.13.0'.
Adding 'Octokit 0.13.0' to ConsoleApplication13.
Successfully added 'Octokit 0.13.0' to ConsoleApplication13.
```

I know that `$error[0].Exception.ToString()` was for the first case, anyway I've executed it also now. Here the result:
```PowerShell
PM> $error[0].Exception.ToString()
System.InvalidOperationException: Failed to add reference to 'System.Net.Http'. Please make sure that it is in the Global Assembly Cache. ---> System.NullReferenceException
: Object reference not set to an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.FSharp.ProjectSystem.AssemblyReferenceNode.AddToProjectFileAndTryResolve(String assemblyInclude)
   at Microsoft.VisualStudio.FSharp.ProjectSystem.AssemblyReferenceNode..ctor(Int32 dummy, ProjectNode root, String assemblyName)
   at Microsoft.VisualStudio.FSharp.ProjectSystem.ReferenceContainerNode.CreateAssemblyReferenceNode(String assemblyInclude, AddReferenceDialogTab tab, Boolean isFullPath)
   at Microsoft.VisualStudio.FSharp.ProjectSystem.ReferenceContainerNode.CreateFileComponent(VSCOMPONENTSELECTORDATA selectorData, AddReferenceDialogTab tab)
   at Microsoft.VisualStudio.FSharp.ProjectSystem.ReferenceContainerNode.CreateReferenceNode(VSCOMPONENTSELECTORDATA selectorData)
   at Microsoft.VisualStudio.FSharp.ProjectSystem.ReferenceContainerNode.AddReferenceFromSelectorData(VSCOMPONENTSELECTORDATA selectorData)
   at Microsoft.VisualStudio.FSharp.ProjectSystem.Automation.OAReferences.<>c__DisplayClass1.<Add>b__0()
   at Microsoft.VisualStudio.Shell.InvokableFunction`1.InvokeMethod()
   at Microsoft.VisualStudio.Shell.InvokableBase.Invoke()
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Shell.ThreadHelper.InvokeOnUIThread(InvokableBase invokable)
   at Microsoft.VisualStudio.Shell.ThreadHelper.Invoke[TResult](Func`1 method)
   at Microsoft.VisualStudio.FSharp.ProjectSystem.Automation.OAReferences.Add(String bstrPath)
   at NuGet.VisualStudio.VsProjectSystem.AddGacReference(String name)
   at NuGet.VisualStudio.FSharpProjectSystem.AddGacReference(String name)
   at NuGet.VisualStudio.VsProjectSystem.AddFrameworkReference(String name)
   --- End of inner exception stack trace ---
   at NuGet.VisualStudio.VsProjectSystem.AddFrameworkReference(String name)
   at NuGet.ProjectManager.ExtractPackageFilesToProject(IPackage package)
   at NuGet.ProjectManager.AddPackageReferenceToProject(IPackage package)
   at NuGet.ProjectManager.Execute(PackageOperation operation)
   at NuGet.ProjectManager.Execute(IPackage package, IPackageOperationResolver resolver)
   at NuGet.ProjectManager.AddPackageReference(IPackage package, Boolean ignoreDependencies, Boolean allowPrereleaseVersions)
   at NuGet.VisualStudio.VsPackageManager.<>c__DisplayClass83.<AddPackageReference>b__85()
   at NuGet.VisualStudio.VsPackageManager.RunProjectAction(IProjectManager projectManager, Action action)
   at NuGet.VisualStudio.VsPackageManager.AddPackageReference(IProjectManager projectManager, IPackage package, Boolean ignoreDependencies, Boolean allowPrereleaseVersions)
   at NuGet.VisualStudio.VsPackageManager.<>c__DisplayClass3.<InstallPackage>b__7()
   at NuGet.VisualStudio.VsPackageManager.RunSolutionAction(Action action)
   at NuGet.VisualStudio.VsPackageManager.InstallPackage(IProjectManager projectManager, String packageId, SemanticVersion version, Boolean ignoreDependencies, Boolean allo
wPrereleaseVersions, Boolean skipAssemblyReferences, ILogger logger)
   at NuGet.VisualStudio.VsPackageManager.InstallPackage(IProjectManager projectManager, String packageId, SemanticVersion version, Boolean ignoreDependencies, Boolean allo
wPrereleaseVersions, ILogger logger)
   at NuGet.PowerShell.Commands.InstallPackageCommand.InstallPackage(IVsPackageManager packageManager)
   at NuGet.PowerShell.Commands.InstallPackageCommand.ProcessRecordCore()
   at NuGet.PowerShell.Commands.NuGetBaseCommand.ProcessRecord()
PM> 
```

If you want, I can try lately if I can reproduce the problem and post again `$error[0].Exception.ToString()` result.

**Comment by shiftkey** [comment] 2015-06-19 23:29
@khellang when you're seeing it fail, what sort of project setup are you trying to add it to?

**Comment by khellang** [comment] 2015-06-20 00:01
@shiftkey It's been a while since I saw it, but in my previous job I used to get it all the time (when installing packages referencing System.Net.Http). I can't really remember anything special about the project setup, just a regular .NET 4.5 class library or web app, all in C#.

**Comment by khellang** [comment] 2015-06-20 00:02
@shiftkey There were PCLs involved in the sln though. Maybe even referenced by the projects, but I can't imagine why that would matter... :confused:

**Comment by gep13** [comment] 2015-08-17 20:28
I have just ran into this same problem.  Using Visual Studio 2015.  Was able to install the package successfully from the Package Manager Console, but not through the Manage Nuget Packages UI.

**Comment by shiftkey** [comment] 2015-08-19 00:17
> Was able to install the package successfully from the Package Manager Console, but not through the Manage Nuget Packages UI.

I guess I need to raise this upstream if it's still around. Thanks for the extra details all.

**Comment by gep13** [comment] 2015-08-19 06:46
Sorry about all the notifications about my commit comment.  I didn't realise that they would show up here :smile_cat:

**Comment by shiftkey** [comment] 2016-03-11 07:38
I've kinda sat on this for a while rather than report it upstream so maybe it's been fixed, but if someone is keen to confirm it's still occurring on NuGet v3 I'll help them to navigate the process of reporting this.

**Comment by SeanKilleen** [comment] 2017-01-09 15:55
Given @shiftkey's last comments on this and that it's > 6 months old, should we close this out?

**Comment by shiftkey** [comment] 2017-01-09 22:50
Yep. And with the port to .NET Core that's underway, the change to use the `System.Net.Http` NuGet package instead of directly referencing `System.Net.Http` as mentioned in https://github.com/octokit/octokit.net/issues/1419#issuecomment-267457741 should resolve this.

**Closed by shiftkey** 2017-01-09 22:50 UTC
Labels: bug, up-for-grabs

**Comment by steveoh** [comment] 2018-08-16 20:04
coworker hit this today on a fresh vs2017 install.


![image](https://user-images.githubusercontent.com/325813/44232065-3d766580-a15d-11e8-9b21-691a45df742d.png)

He added system.net.http manually

**Comment by ryangribble** [comment] 2018-08-16 21:04
Hi @steveoh what target framework was the project and what version of octokit package?

**Comment by steveoh** [comment] 2018-08-16 21:10
@ryangribble target framework is 4.6.1 and version 0.31 of octokit

**Comment by steveoh** [comment] 2018-08-16 21:26
coworker hit this today on a fresh vs2017 install.

![image](https://user-images.githubusercontent.com/325813/44232065-3d766580-a15d-11e8-9b21-691a45df742d.png)

He added system.net.http manually

@ryangribble 

target framework 4.6.1
octokit version 0.31
vs version 15.8
dotnet info
![image](https://user-images.githubusercontent.com/325813/44235984-b7f8b280-a168-11e8-84f4-72dfd1061291.png)

**Comment by ryangribble** [comment] 2018-08-17 11:00
Im on VS2017 15.7.4 and can't reproduce this.  I added Octokit 0.31 to an sdk format net461 project and it worked fine.  I also tried a VS2015 csproj format .NET Framework 4.6.1 targetted project, and again it worked ok.

Is your project existing or brand new?  Is it the new Sdk style csproj project or the older VS2015 style?  Is it repeatable/can you share the csproj?  Or provide a minimal repro?
