### ISSUE TITLE
"Object reference not set to an instance of an object." when calling Actions.Workflows.Jobs.List

### ISSUE THREAD

**Issue by peeeteeer** [octokit/octokit.net#2713] opened 2023-05-19 21:12 UTC
I'm getting a "Object reference not set to an instance of an object." when calling Actions.Workflows.Jobs.List. Stack Trace is a as follows...

"   at lambda_method660(Closure , Object , Object )\r\n   at Octokit.Reflection.ReflectionUtils.<>c__DisplayClass41_0.<GetSetMethodByExpression>b__0(Object source, Object val) in /_/Octokit/SimpleJson.cs:line 2068\r\n   at Octokit.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type) in /_/Octokit/SimpleJson.cs:line 1488\r\n   at Octokit.Internal.SimpleJsonSerializer.GitHubSerializerStrategy.DeserializeObject(Object value, Type type) in /_/Octokit/Http/SimpleJsonSerializer.cs:line 205\r\n   at Octokit.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type) in /_/Octokit/SimpleJson.cs:line 1515\r\n   at Octokit.Internal.SimpleJsonSerializer.GitHubSerializerStrategy.DeserializeObject(Object value, Type type) in /_/Octokit/Http/SimpleJsonSerializer.cs:line 205\r\n   at Octokit.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type) in /_/Octokit/SimpleJson.cs:line 1488\r\n   at Octokit.Internal.SimpleJsonSerializer.GitHubSerializerStrategy.DeserializeObject(Object value, Type type) in /_/Octokit/Http/SimpleJsonSerializer.cs:line 205\r\n   at Octokit.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type) in /_/Octokit/SimpleJson.cs:line 1515\r\n   at Octokit.Internal.SimpleJsonSerializer.GitHubSerializerStrategy.DeserializeObject(Object value, Type type) in /_/Octokit/Http/SimpleJsonSerializer.cs:line 205\r\n   at Octokit.SimpleJson.DeserializeObject(String json, Type type, IJsonSerializerStrategy jsonSerializerStrategy) in /_/Octokit/SimpleJson.cs:line 584\r\n   at Octokit.SimpleJson.DeserializeObject[T](String json, IJsonSerializerStrategy jsonSerializerStrategy) in /_/Octokit/SimpleJson.cs:line 596\r\n   at Octokit.Internal.SimpleJsonSerializer.Deserialize[T](String json) in /_/Octokit/Http/SimpleJsonSerializer.cs:line 22\r\n   at Octokit.Internal.JsonHttpPipeline.DeserializeResponse[T](IResponse response) in /_/Octokit/Http/JsonHttpPipeline.cs:line 62\r\n   at Octokit.Connection.Run[T](IRequest request, CancellationToken cancellationToken) in /_/Octokit/Http/Connection.cs:line 687\r\n   at Octokit.ApiConnection.GetPage[TU](Uri uri, IDictionary`2 parameters, String accepts, ApiOptions options) in /_/Octokit/Http/ApiConnection.cs:line 642\r\n   at Octokit.ApiConnection.<>c__DisplayClass18_0`1.<<GetAll>b__0>d.MoveNext() in /_/Octokit/Http/ApiConnection.cs:line 212\r\n--- End of stack trace from previous location ---\r\n   at Octokit.ApiPagination.GetAllPages[T](Func`1 getFirstPage, Uri uri)\r\n   at Octokit.ActionsWorkflowJobsClient.List(String owner, String name, Int64 runId, WorkflowRunJobsRequest workflowRunJobsRequest, ApiOptions options) in /_/Octokit/Clients/ActionsWorkflowJobsClient.cs:line 126\r\n   at deployment_api.activities.DeployActivity.DeployActivityMethod(OrchestrationParameters pars, ILogger log)

Calling the REST API with Postman works and returns the expected result...

Any idea?

**Comment by timheuer** [comment] 2023-05-24 22:20
I'm getting this as well when it hits a failed run -- when it is on successful runs it is fine, but a failed run throws here as well.

**Comment by timheuer** [comment] 2023-05-24 22:42
I'm not familiar with the codebase but this gets called a lot but my exception is happening here:
![image](https://github.com/octokit/octokit.net/assets/4821/e77b7f08-11a5-4937-a16f-c679ef7fff49)

**Comment by vuryleo** [comment] 2023-06-14 08:35
is the `runnername` etc the cause?

ref #2724

**Comment by redoz** [comment] 2023-06-23 07:05
This appears fixed in 6.10, I haven't been able to reproduce it since the update.

**Comment by kfcampbell** [comment] 2023-06-23 18:23
@redoz thanks for sharing; I'll close this issue for now. If it pops up again, we can reopen.

**Closed by kfcampbell** 2023-06-23 18:23 UTC
Labels: Priority: Normal, Status: Up for grabs, Type: Bug

**Comment by peeeteeer** [comment] 2023-06-26 21:42
Updated to 6.10 - seems to work - thanks :)
