### ISSUE TITLE
[BUG]: Intermittent Bad Credentials with same PAT token

### ISSUE THREAD

**Issue by thomhurst** [octokit/octokit.net#2786] opened 2023-09-26 12:06 UTC
### What happened?

Intermittent Bad Credentials - But I'm using the same PAT token

It's passed in through my pipeline secrets. Sometimes it doesn't fail. Other times I get a bad credentials error.

### Versions

8.0.0

### Relevant log output

```shell
Octokit.AuthorizationException: Bad credentials
   at Octokit.Connection.HandleErrors(IResponse response) in /_/Octokit/Http/Connection.cs:line 729
   at Octokit.Connection.RunRequest(IRequest request, CancellationToken cancellationToken, Func`2 preprocessResponseBody) in /_/Octokit/Http/Connection.cs:line 710
   at Octokit.Connection.Run[T](IRequest request, CancellationToken cancellationToken, Func`2 preprocessResponseBody) in /_/Octokit/Http/Connection.cs:line 695
   at Octokit.Internal.ReadOnlyPagedCollection`1.GetNextPage() in /_/Octokit/Http/ReadOnlyPagedCollection.cs:line 38
   at Octokit.ApiPagination.GetAllPages[T](Func`1 getFirstPage, Uri uri) in /_/Octokit/Clients/ApiPagination.cs:line 26
   at Octokit.ActionsWorkflowRunsClient.ListByWorkflow(String owner, String name, String workflowFileName, WorkflowRunsRequest workflowRunsRequest, ApiOptions options) in /_/Octokit/Clients/ActionsWorkflowRunsClient.cs:line 425
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nickfloyd** [comment] 2023-09-26 14:10
Hey @thomhurst, currently Ocotkit.net has no knowledge of GitHub REST API rate limits. Our future goals are to make an SDK more robust by implementing an understanding of rate limiting and retries using the rate limit APIs.

All that to say - it does look like that's what's happening here but the messaging is not really helpful at all.  I feel like we could do a much better job with messaging here.  If that's the case we should transform this issue into more of a feat/improvement (it's almost a bug IMO) to improve how we communicate to the consumer when things like rate limiting occurs?

However, this may in fact be a bug given we do have [handling](https://github.com/octokit/octokit.net/blob/958bc5f1f87cd97cd8520ac74f958c2df12903b3/Octokit/Http/Connection.cs#L784C39-L784C39) for [primary](https://github.com/octokit/octokit.net/blob/958bc5f1f87cd97cd8520ac74f958c2df12903b3/Octokit/Exceptions/RateLimitExceededException.cs#L22) and [secondary](https://github.com/octokit/octokit.net/blob/958bc5f1f87cd97cd8520ac74f958c2df12903b3/Octokit/Exceptions/SecondaryRateLimitExceededException.cs#L20) RateLImitExceptions. 

The REST API should be sending back a [401s for Authorization](https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#authentication) errors and [403s for forbidden](https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#rate-limiting) (which seems more appropriate for a rate limit exception) - this should all be handled [here](https://github.com/octokit/octokit.net/blob/958bc5f1f87cd97cd8520ac74f958c2df12903b3/Octokit/Http/Connection.cs#L775) - perhaps there is an issue with ordinality. 

Lastly, we could be seeing a side effect of how paging is "working".  The API will begin sending back 403's if there were several attempts with [invalid credentials](https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#failed-login-limit).  If our paging logic isn't making the requests properly with a token than this could be happening as well.

We need more research here to rule out all of this speculation.  I know it happens to  you incrementally we're you ever able to get a solid repo case?

**Comment by thomhurst** [comment] 2023-09-26 15:24
No unfortunately I can't get a solid reproduction :(

**Comment by mattem** [comment] 2023-09-26 19:19
Also been experiencing this, started approx 14:00:00 ET yesterday (Monday 25th) from the looks of our monitoring.

I've been able to reproduce the issue with a new PAT, and simply calling the `rate_limit` endpoint.
As a test we've been calling the rate limit API every 10 seconds, and will see the "Bad credentials" error after an undefined amount of time.

```
(14:59:13) Start request
request {
  method: 'GET',
  baseUrl: 'https://api.github.com/',
  headers: {
    accept: 'application/vnd.github.v3+json',
    'user-agent': 'octokit-rest.js/20.0.1 octokit-core.js/5.0.0 Node.js/18.17.1 (darwin; arm64)'
  },
  mediaType: { format: '', previews: [] },
  request: { hook: [Function: bound bound register] },
  url: '/rate_limit'
}
GET /rate_limit - 401 in 207ms
/private/var/tmp/_bazel_matt/6659d1da76c274502913a8a29ab51672/execroot/aspect_silo/bazel-out/darwin_arm64-fastbuild/bin/node_modules/.aspect_rules_js/@octokit+request@8.1.0/node_modules/@octokit/request/dist-node/index.js:112
      const error = new import_request_error.RequestError(toErrorMessage(data), status, {
                    ^

RequestError [HttpError]: Bad credentials
```

Currently trying with plain `cURL` to see if it's actually Oktokit that's the issue.

**Comment by nickfloyd** [comment] 2023-10-05 20:07
A similar [issue](https://github.com/octokit/octokit.rb/issues/1634) has been raised on Octokit.rb.  The two could possibly be related.

**Comment by nickfloyd** [comment] 2023-10-17 17:20
From your research and mine it seems to be a **mechanism** (how things work to prevent service attacks perhaps) or **potential issue** with authentication on the GitHub REST API side.  I will highlight this with the API team but as of now the best **course of action is to submit a [support ticket](https://support.github.com/) with GitHub** so that they can get this effectively tracked and routed to the correct team so that it can be quickly answered/addressed.

Again, sorry for all of the trouble here.

**Comment by nickfloyd** [comment] 2023-10-17 17:51
Hey @mattem & @thomhurst,
We just took a look at something and saw a feature that was getting released at or near the time that you reported experiencing this - it was done as a percentage based rollout so it's possible that you could've hit various clusters with your requests as the rollout happened (this is mostly speculation though).

Let me know if you're still experiencing the issue. Thanks!

**Comment by nickfloyd** [comment] 2023-10-18 12:50
Thanks for the follow up.  We'll close this for now, but feel free to re open it if you run into the issue again.

**Closed by nickfloyd** 2023-10-18 12:50 UTC
Labels: Type: Bug, Type: Support
