### ISSUE TITLE
Pull File Locally

### ISSUE THREAD

**Issue by jackahuja** [octokit/octokit.net#773] opened 2015-03-23 13:26 UTC
Using Octokit.Net, I am trying to login to our Enterprise github repository and pull the file locally. But as I fire this statement var contents = await client.Repository.Content.GetContents("owner", "reponame", "FilePath"); This thread moves out of the async method and execution stops.
Am I missing any thing here.

**Comment by shiftkey** [comment] 2015-03-24 21:14
> This thread moves out of the async method 

This sounds like the intended behaviour of async/await...

> and execution stops.

But this definitely isn't right at all.

A couple of questions:

 - If you set a breakpoint on the line after the method, do you ever see it get hit?
 - Could execution be stopping due to an unhandled or first-chance exception? The Output window might have some clues.
 - What if you were to try a GitHub resource instead of a GitHub Enterprise URL? Does the same thing happen?

**Comment by jackahuja** [comment] 2015-03-27 06:14
I am not getting any content or exception for the variable. By GitHub resourse do you mean GitHub local client? Also I am getting the status of the thread as 
Id = 1, Status = WaitingForActivation, Method = "{null}", Result = "{Not yet computed}".

**Comment by shiftkey** [comment] 2015-03-31 12:02
What about if you do this?

```
var contents = client.Repository.Content.GetContents("owner", "reponame", "FilePath"); 
contents.Wait();
var result = contents.Result;
```

It's hard to say what might be causing the task to not execute (I'm not sure what sort of application you're running here) but this is how you can force the program to block until the task completes.

> By GitHub resourse do you mean GitHub local client?

Rather than point to your GitHub Enterprise environment, could you try it against GitHub?

```
var github = new GitHubClient(new ProductHeaderValue("OctokitTests"));
var readme = await github.Repository.Content.GetReadme("octokit", "octokit.net");
Debug.Assert("README.md" == readme.Name);
```

If that works, perhaps there's some networking-specific problem at play here...

**Comment by jackahuja** [comment] 2015-03-31 16:21
Hi, thanks, I will try this and let you know.

**Comment by shiftkey** [comment] 2015-04-06 08:27
Closing this until more information is made available

**Closed by shiftkey** 2015-04-06 08:27 UTC
