### ISSUE TITLE
missing "closed_by" data in response for single issue request 

### ISSUE THREAD

**Issue by lbrader** [octokit/octokit.net#1349] opened 2016-06-07 23:47 UTC
https://github.com/octokit/octokit.net/blob/master/docs/issues.md

I'm retrieving a list of issues from a repository and if it's close I retrieve the single issue. The issue value returned from the single issue response - does not contain "Close_by" fields.

var issue = await client.Issue.Get("octokit", "octokit.net",#_of_issue);

The "issue" response is incorrect.

Reference https://developer.github.com/v3/issues/#get-a-single-issue for the expected JSON response format. Inside the response the "closed_by" value is expected - doesn't exist.
{
   // removed for clarity
  "closed_by": {
    "login": "octocat",
    "id": 1,
    "avatar_url": "https://github.com/images/error/octocat_happy.gif",
    "gravatar_id": "",
    "url": "https://api.github.com/users/octocat",
    "html_url": "https://github.com/octocat",
    "followers_url": "https://api.github.com/users/octocat/followers",
    "following_url": "https://api.github.com/users/octocat/following{/other_user}",
    "gists_url": "https://api.github.com/users/octocat/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/octocat/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/octocat/subscriptions",
    "organizations_url": "https://api.github.com/users/octocat/orgs",
    "repos_url": "https://api.github.com/users/octocat/repos",
    "events_url": "https://api.github.com/users/octocat/events{/privacy}",
    "received_events_url": "https://api.github.com/users/octocat/received_events",
    "type": "User",
    "site_admin": false
  }

**Comment by ryangribble** [comment] 2016-06-08 21:34
duplicate of #1350

**Closed by ryangribble** 2016-06-08 21:34 UTC
