### ISSUE TITLE
Still not strong named at nuget.org ?

### ISSUE THREAD

**Issue by wangyoutian** [octokit/octokit.net#2382] opened 2021-12-13 15:57 UTC
After I installed octokit from nuget.org, I exported the meta of the installed dll and found it's  still not strong-named. The dumped meta is :

"Octokit, Version=0.50.0.0, Culture=neutral, PublicKeyToken=null"

Being unstrong-named, it brings about some issue in my project, which is strong named. 

I saw at this repo that whether to strong-name has been discussed and the decision to strong-name is made. So where can I found the strong-name version?

I pulled this repo to my local computer. I found the source code is not strong named. I tried to strong-name it locally; it is done. But I think I would prefer the official strong name version to avoid some issues such as mismatched ".snk" file.

Any advice? 

Thanks.

**Comment by nickfloyd** [comment] 2022-04-25 20:46
Possble duplicate of: https://github.com/octokit/octokit.net/issues/1604

**Comment by JonruAlveus** [comment] 2022-10-11 04:34
We are now strong signed 👍

**Closed by JonruAlveus** 2022-10-11 04:34 UTC
Labels: improvement, duplicate
